name: hoop
description: "A new Flutter project."

publish_to: 'none' 
version: 0.0.1+10

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  swipe_cards: ^2.0.0
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  chewie:
  animations: ^2.0.8
  shimmer: ^3.0.0
  story_view: 
  url_launcher: ^6.0.13
  flutter_inappwebview: ^6.1.5
  youtube_player_flutter: ^9.1.3
  google_mlkit_face_detection:
  flutter_callkit_incoming: ^3.0.0
  qr_flutter: 
  crypto: ^3.0.0
  flutter_svg:
  device_info_plus: ^9.0.0
  geolocator: ^11.0.0
  uuid: ^4.4.0
  camera: 
  image: ^4.0.17
  jwt_decoder:
  file_picker: ^10.3.8
  package_info_plus:
  hive:
  sensors_plus:
  record: ^4.4.0
  smart_overlay_menu: ^1.0.3
  cached_network_image_plus: 
  image_picker: ^1.1.1
  video_player: ^2.8.3  
  http: ^1.2.2
  just_audio:  
  flutter_webrtc: ^1.2.1
  video_thumbnail:
  permission_handler: ^11.1.0
  logger: ^2.0.2
  share_plus: 
  onesignal_flutter: ^5.3.5
  emoji_picker_flutter: ^3.0.5
  iconsax:
  provider: ^6.1.2  
  flutter_dotenv: ^5.1.0 
  socket_io_client: ^3.1.3
  hive_flutter: ^1.1.0
  local_auth: ^3.0.0
  audio_session: ^0.1.11  
  vibration: ^3.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
